name: Bug report
description: Create a report to help us improve
labels: ["Unconfirmed bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: markdown
    attributes:
      value: >-
        # Minetest Version

  - type: input
    id: minetest_version
    attributes:
      label: Minetest Version
      description: |
        If you are on a devel version, please add git commit hash.
        You can use `minetest --version` to find it.
      placeholder: "ex: 5.4.1"
    validations:
      required: true

  - type: markdown
    attributes:
      value: >-
        # OS / Hardware

  - type: input
    id: env_os
    attributes:
      label: Operating System(s)
      description: |
        Ex: Windows 10, Ubuntu 20.04
    validations:
      required: true

  - type: input
    id: env_cpu
    attributes:
      label: CPU
      description: |
        Ex: Intel i7
    validations:
      required: false

  - type: textarea
    id: env_gpu
    attributes:
      label: GPU / OpenGL
      description: For graphical issues only
      value: |
        GPU model:
        OpenGL version:
    validations:
      required: false

  - type: markdown
    attributes:
      value: >-
        # The Bug

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: >-
        Describe your problem here.
        What is the current behaviour, and what did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Explain how the problem happened
    validations:
      required: true
